#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Run ConvTransformer-v3a for L=100 on validation only.

This script is based on the v2 notebook:

    notebooks/11_convtransformer_binary_detection_localization.ipynb

The only methodological change introduced here is the input representation:

    ConvTransformer-v2:  (N, 99, 1)
    ConvTransformer-v3a: (N, 99, 6)

The six-channel representation is produced by:

    scripts.feature_engineering.build_multichannel_features

No test evaluation is performed in this script. The output directory is limited
to:

    results/convtransformer_v3_ablation/v3a_seed42/validation_metrics.csv
    results/convtransformer_v3_ablation/v3a_seed42/config_used.yaml

Scientific note:
ConvTransformer-v3a se evalúa inicialmente en validación con una única semilla
para comprobar si la entrada multicanal justifica continuar con las variantes
v3b y v3c.
"""

from __future__ import annotations

import argparse
import json
import random
import sys
from pathlib import Path
from typing import Any

import h5py
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    f1_score,
    mean_absolute_error,
    mean_squared_error,
    precision_score,
    recall_score,
)
from tensorflow.keras import callbacks, layers, metrics, models, optimizers


PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from scripts.feature_engineering import CHANNEL_NAMES, build_multichannel_features  # noqa: E402


RANDOM_SEED = 42
LENGTH = 100
DX_LENGTH = LENGTH - 1
N_INPUT_CHANNELS = 6
MIN_SEGMENT_LENGTH = 20
VALID_DX_MIN = MIN_SEGMENT_LENGTH - 1
VALID_DX_MAX = LENGTH - MIN_SEGMENT_LENGTH - 1

MODEL_NAMES = ["ATTM", "CTRW", "FBM", "LW", "SBM"]
MODEL_MAP = {i: name for i, name in enumerate(MODEL_NAMES)}
TRANSITIONS = [(m1, m2) for m1 in MODEL_NAMES for m2 in MODEL_NAMES if m1 != m2]
TRANSITION_ORDER = [f"{m1} -> {m2}" for m1, m2 in TRANSITIONS]

BATCH_SIZE = 256
MAX_EPOCHS = 100
LEARNING_RATE = 1e-3
LOSS_WEIGHTS = [2.0, 1.0]
THRESHOLDS = np.round(np.arange(0.05, 0.951, 0.025), 3)
MONITOR_METRIC = "val_selection_score"


def set_global_seed(seed: int) -> None:
    """Fix the random seed for Python, NumPy and TensorFlow."""
    random.seed(seed)
    np.random.seed(seed)
    tf.random.set_seed(seed)
    try:
        tf.keras.utils.set_random_seed(seed)
    except AttributeError:
        pass


def decode_model(value: Any) -> str:
    """Decode model labels stored as bytes, strings or integer IDs."""
    if isinstance(value, bytes):
        return value.decode("utf-8")
    if isinstance(value, str):
        return value
    return MODEL_MAP[int(value)]


def load_split(file_path: Path, split_name: str) -> tuple[np.ndarray, np.ndarray, np.ndarray, pd.DataFrame]:
    """
    Load a train/validation split from the v2 HDF5 files.

    The raw increment signal is returned with shape (N, 99, 1). The
    multichannel feature construction is applied later, so this function does
    not use labels to build input features.
    """
    if not file_path.exists():
        raise FileNotFoundError(
            f"Missing {split_name} file: {file_path}\n"
            "Expected the binary L=100 dataset generated by the v2 pipeline."
        )

    with h5py.File(file_path, "r") as file:
        dx = file["dx"][:].astype("float32")
        has_cp = file["has_changepoint"][:].astype("float32")
        cp = file["cp"][:].astype("int16")
        cp_dx = file["cp_dx"][:].astype("int16") if "cp_dx" in file else (cp - 1).astype("int16")
        model1 = file["model1"][:]
        model2 = file["model2"][:]

    if dx.ndim == 2:
        dx = dx[:, :, None]

    if dx.shape[1:] != (DX_LENGTH, 1):
        raise ValueError(f"Expected dx shape (N, {DX_LENGTH}, 1), got {dx.shape}.")

    cp_class = np.where(has_cp == 1, cp_dx, 0).astype("int32")

    metadata = pd.DataFrame(
        {
            "split": split_name,
            "has_changepoint": has_cp.astype(int),
            "cp": cp,
            "cp_dx": cp_dx,
            "cp_class": cp_class,
            "model1": [decode_model(value) for value in model1],
            "model2": [decode_model(value) for value in model2],
        }
    )
    metadata["transition"] = np.where(
        metadata["has_changepoint"] == 1,
        metadata["model1"] + " -> " + metadata["model2"],
        metadata["model1"] + " (no changepoint)",
    )

    return dx, has_cp.reshape(-1, 1).astype("float32"), cp_class.astype("int32"), metadata


def balanced_subset(
    dx: np.ndarray,
    y_has: np.ndarray,
    y_cp_class: np.ndarray,
    metadata: pd.DataFrame,
    n_total: int,
    seed: int,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, pd.DataFrame]:
    """
    Select a balanced subset for quick validation runs.

    The subset keeps half changepoint and half no-changepoint trajectories when
    possible. Positive trajectories are distributed across ordered transitions;
    negative trajectories are distributed across the first diffusion model.

    This function is only used to reduce runtime during exploratory validation.
    It does not use labels to build input features.
    """
    if n_total <= 0:
        raise ValueError("n_total must be positive.")

    if n_total >= len(dx):
        return dx, y_has, y_cp_class, metadata.reset_index(drop=True)

    rng = np.random.default_rng(seed)
    n_with = n_total // 2
    n_without = n_total - n_with

    with_meta = metadata[metadata["has_changepoint"] == 1]
    without_meta = metadata[metadata["has_changepoint"] == 0]

    selected: list[int] = []

    per_transition = n_with // len(TRANSITION_ORDER)
    extra_transition = n_with % len(TRANSITION_ORDER)
    for i, transition in enumerate(TRANSITION_ORDER):
        group = with_meta[with_meta["transition"] == transition].index.to_numpy()
        k = per_transition + (1 if i < extra_transition else 0)
        if len(group) == 0 or k == 0:
            continue
        selected.extend(rng.choice(group, size=min(k, len(group)), replace=False).tolist())

    per_model = n_without // len(MODEL_NAMES)
    extra_model = n_without % len(MODEL_NAMES)
    for i, model_name in enumerate(MODEL_NAMES):
        group = without_meta[without_meta["model1"] == model_name].index.to_numpy()
        k = per_model + (1 if i < extra_model else 0)
        if len(group) == 0 or k == 0:
            continue
        selected.extend(rng.choice(group, size=min(k, len(group)), replace=False).tolist())

    selected_array = np.array(selected, dtype=int)
    if len(selected_array) == 0:
        raise ValueError("Balanced subset selection produced no examples.")
    rng.shuffle(selected_array)

    return (
        dx[selected_array],
        y_has[selected_array],
        y_cp_class[selected_array],
        metadata.loc[selected_array].reset_index(drop=True),
    )


def make_sample_weights(y_has: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Mask localization loss on no-changepoint trajectories."""
    y_flat = y_has.reshape(-1).astype("float32")
    return np.ones_like(y_flat, dtype="float32"), y_flat.astype("float32")


def make_dataset(
    x: np.ndarray,
    y_has: np.ndarray,
    y_cp_class: np.ndarray,
    batch_size: int,
    training: bool = False,
) -> tf.data.Dataset:
    """Build the TensorFlow dataset with two outputs and localization masking."""
    y = (y_has.astype("float32"), y_cp_class.astype("int32"))
    sample_weight = make_sample_weights(y_has)
    dataset = tf.data.Dataset.from_tensor_slices((x, y, sample_weight))
    if training:
        dataset = dataset.shuffle(min(10_000, len(x)), seed=RANDOM_SEED, reshuffle_each_iteration=True)
    return dataset.batch(batch_size).prefetch(tf.data.AUTOTUNE)


@tf.keras.utils.register_keras_serializable(package="Changepoint")
class ValidPositionMask(layers.Layer):
    """Mask invalid changepoint positions before softmax."""

    def __init__(self, sequence_length: int, valid_min: int, valid_max: int, **kwargs: Any):
        super().__init__(**kwargs)
        self.sequence_length = int(sequence_length)
        self.valid_min = int(valid_min)
        self.valid_max = int(valid_max)

    def call(self, logits: tf.Tensor) -> tf.Tensor:
        positions = tf.range(self.sequence_length)
        valid = tf.logical_and(positions >= self.valid_min, positions <= self.valid_max)
        valid = tf.cast(valid, tf.float32)
        mask = (1.0 - valid) * (-1e9)
        return logits + mask[tf.newaxis, :]

    def get_config(self) -> dict[str, Any]:
        config = super().get_config()
        config.update(
            {
                "sequence_length": self.sequence_length,
                "valid_min": self.valid_min,
                "valid_max": self.valid_max,
            }
        )
        return config


@tf.keras.utils.register_keras_serializable(package="Changepoint")
class LastStep(layers.Layer):
    """Return the last temporal state."""

    def call(self, inputs: tf.Tensor) -> tf.Tensor:
        return inputs[:, -1, :]


@tf.keras.utils.register_keras_serializable(package="Changepoint")
class SqueezeLastAxis(layers.Layer):
    """Remove the final singleton channel axis."""

    def call(self, inputs: tf.Tensor) -> tf.Tensor:
        return tf.squeeze(inputs, axis=-1)


@tf.keras.utils.register_keras_serializable(package="Changepoint")
class PositionalEmbedding(layers.Layer):
    """Learned positional embedding used by ConvTransformer-v2."""

    def __init__(self, sequence_length: int, d_model: int, **kwargs: Any):
        super().__init__(**kwargs)
        self.sequence_length = int(sequence_length)
        self.d_model = int(d_model)
        self.position_embedding = layers.Embedding(
            input_dim=self.sequence_length,
            output_dim=self.d_model,
            name="position_embedding_table",
        )

    def call(self, inputs: tf.Tensor) -> tf.Tensor:
        positions = tf.range(start=0, limit=self.sequence_length, delta=1)
        embedded_positions = self.position_embedding(positions)
        return inputs + embedded_positions[tf.newaxis, :, :]

    def get_config(self) -> dict[str, Any]:
        config = super().get_config()
        config.update({"sequence_length": self.sequence_length, "d_model": self.d_model})
        return config


@tf.keras.utils.register_keras_serializable(package="Changepoint")
def sparse_ce_localization(y_true: tf.Tensor, y_pred: tf.Tensor) -> tf.Tensor:
    """Sparse cross-entropy for the discrete changepoint-position head."""
    y_true = tf.reshape(tf.cast(y_true, tf.int32), [-1])
    n_positions = tf.shape(y_pred)[1]
    y_true = tf.clip_by_value(y_true, 0, n_positions - 1)
    y_pred = tf.clip_by_value(y_pred, 1e-7, 1.0 - 1e-7)
    batch_size = tf.shape(y_pred)[0]
    gather_indices = tf.stack([tf.range(batch_size, dtype=tf.int32), y_true], axis=1)
    true_prob = tf.gather_nd(y_pred, gather_indices)
    return -tf.math.log(true_prob)


@tf.keras.utils.register_keras_serializable(package="Changepoint")
def weighted_binary_crossentropy_no_cp(y_true: tf.Tensor, y_pred: tf.Tensor) -> tf.Tensor:
    """Weighted binary cross-entropy copied from ConvTransformer-v2."""
    y_true = tf.cast(tf.reshape(y_true, [-1]), tf.float32)
    y_pred = tf.cast(tf.reshape(y_pred, [-1]), tf.float32)
    y_pred = tf.clip_by_value(y_pred, 1e-7, 1.0 - 1e-7)

    positive_weight = tf.constant(1.0, dtype=tf.float32)
    negative_weight = tf.constant(1.8, dtype=tf.float32)

    positive_loss = -positive_weight * y_true * tf.math.log(y_pred)
    negative_loss = -negative_weight * (1.0 - y_true) * tf.math.log(1.0 - y_pred)
    return tf.reduce_mean(positive_loss + negative_loss)


def conv_stem_block(x: tf.Tensor, d_model: int, dropout_rate: float) -> tf.Tensor:
    """Local Conv1D feature extractor before attention blocks."""
    x = layers.Conv1D(filters=d_model // 2, kernel_size=5, padding="same", name="conv_stem_1")(x)
    x = layers.LayerNormalization(epsilon=1e-6, name="conv_stem_norm_1")(x)
    x = layers.Activation("gelu", name="conv_stem_gelu_1")(x)
    x = layers.Dropout(dropout_rate, name="conv_stem_dropout_1")(x)

    x = layers.Conv1D(filters=d_model, kernel_size=3, padding="same", name="conv_stem_2")(x)
    x = layers.LayerNormalization(epsilon=1e-6, name="conv_stem_norm_2")(x)
    x = layers.Activation("gelu", name="conv_stem_gelu_2")(x)
    x = layers.Dropout(dropout_rate, name="conv_stem_dropout_2")(x)
    return x


def conv_residual_block(
    x: tf.Tensor,
    d_model: int,
    kernel_size: int,
    dropout_rate: float,
    block_id: int,
    dilation_rate: int = 1,
) -> tf.Tensor:
    """Residual Conv1D block that preserves temporal length."""
    residual = x

    y = layers.Conv1D(
        filters=d_model,
        kernel_size=kernel_size,
        padding="same",
        dilation_rate=dilation_rate,
        name=f"conv_residual_{block_id}_conv_1",
    )(x)
    y = layers.LayerNormalization(epsilon=1e-6, name=f"conv_residual_{block_id}_norm_1")(y)
    y = layers.Activation("gelu", name=f"conv_residual_{block_id}_gelu_1")(y)
    y = layers.Dropout(dropout_rate, name=f"conv_residual_{block_id}_dropout_1")(y)

    y = layers.Conv1D(
        filters=d_model,
        kernel_size=kernel_size,
        padding="same",
        dilation_rate=dilation_rate,
        name=f"conv_residual_{block_id}_conv_2",
    )(y)
    y = layers.Dropout(dropout_rate, name=f"conv_residual_{block_id}_dropout_2")(y)

    x = layers.Add(name=f"conv_residual_{block_id}_add")([residual, y])
    x = layers.LayerNormalization(epsilon=1e-6, name=f"conv_residual_{block_id}_norm_2")(x)
    return x


def transformer_encoder_block(
    x: tf.Tensor,
    d_model: int,
    num_heads: int,
    ff_dim: int,
    dropout_rate: float,
    block_id: int,
) -> tf.Tensor:
    """Transformer encoder block copied from ConvTransformer-v2."""
    attention_output = layers.MultiHeadAttention(
        num_heads=num_heads,
        key_dim=d_model // num_heads,
        dropout=dropout_rate,
        name=f"transformer_{block_id}_mha",
    )(x, x)
    attention_output = layers.Dropout(dropout_rate, name=f"transformer_{block_id}_attn_dropout")(attention_output)
    x = layers.Add(name=f"transformer_{block_id}_attn_add")([x, attention_output])
    x = layers.LayerNormalization(epsilon=1e-6, name=f"transformer_{block_id}_attn_norm")(x)

    ffn = layers.Dense(ff_dim, activation="gelu", name=f"transformer_{block_id}_ffn_dense_1")(x)
    ffn = layers.Dropout(dropout_rate, name=f"transformer_{block_id}_ffn_dropout_1")(ffn)
    ffn = layers.Dense(d_model, name=f"transformer_{block_id}_ffn_dense_2")(ffn)
    ffn = layers.Dropout(dropout_rate, name=f"transformer_{block_id}_ffn_dropout_2")(ffn)
    x = layers.Add(name=f"transformer_{block_id}_ffn_add")([x, ffn])
    x = layers.LayerNormalization(epsilon=1e-6, name=f"transformer_{block_id}_ffn_norm")(x)
    return x


def build_convtransformer_v3a_model(
    input_shape: tuple[int, int] = (DX_LENGTH, N_INPUT_CHANNELS),
    d_model: int = 96,
    num_heads: int = 4,
    ff_dim: int = 192,
    num_transformer_blocks: int = 3,
    num_conv_blocks: int = 2,
    conv_kernel_size: int = 5,
    dropout_rate: float = 0.15,
) -> models.Model:
    """
    Build ConvTransformer-v3a.

    Compared with v2, only the input channel count changes from 1 to 6.
    The two task heads are preserved: binary detection (`has_cp`) and
    localization (`cp_dist`).
    """
    inputs = layers.Input(shape=input_shape, name="multichannel_dx_input")
    x = conv_stem_block(inputs, d_model=d_model, dropout_rate=dropout_rate)

    for conv_id in range(1, num_conv_blocks + 1):
        dilation_rate = 1 if conv_id == 1 else 2
        x = conv_residual_block(
            x=x,
            d_model=d_model,
            kernel_size=conv_kernel_size,
            dropout_rate=dropout_rate,
            block_id=conv_id,
            dilation_rate=dilation_rate,
        )

    x = PositionalEmbedding(input_shape[0], d_model, name="positional_embedding")(x)
    x = layers.Dropout(dropout_rate, name="embedding_dropout")(x)

    for block_id in range(1, num_transformer_blocks + 1):
        x = transformer_encoder_block(
            x=x,
            d_model=d_model,
            num_heads=num_heads,
            ff_dim=ff_dim,
            dropout_rate=dropout_rate,
            block_id=block_id,
        )

    avg_pool = layers.GlobalAveragePooling1D(name="average_pooling")(x)
    max_pool = layers.GlobalMaxPooling1D(name="max_pooling")(x)
    last_state = LastStep(name="last_state")(x)

    shared = layers.Concatenate(name="shared_features")([avg_pool, max_pool, last_state])
    shared = layers.Dense(128, activation="gelu", name="shared_dense_1")(shared)
    shared = layers.Dropout(0.25, name="shared_dropout_1")(shared)
    shared = layers.Dense(64, activation="gelu", name="shared_dense_2")(shared)

    det = layers.Dense(64, activation="gelu", name="detection_dense_1")(shared)
    det = layers.Dropout(0.20, name="detection_dropout")(det)
    has_cp = layers.Dense(1, activation="sigmoid", name="has_cp")(det)

    loc = layers.Dense(96, activation="gelu", name="localization_dense_1")(x)
    loc = layers.Dropout(0.15, name="localization_dropout")(loc)
    loc = layers.Dense(48, activation="gelu", name="localization_dense_2")(loc)
    logits = layers.Dense(1, name="localization_logits_dense")(loc)
    logits = SqueezeLastAxis(name="localization_logits")(logits)
    logits = ValidPositionMask(DX_LENGTH, VALID_DX_MIN, VALID_DX_MAX, name="valid_position_mask")(logits)
    cp_dist = layers.Activation("softmax", name="cp_dist")(logits)

    return models.Model(inputs=inputs, outputs=[has_cp, cp_dist], name="convtransformer_v3a_L100")


def compile_model(model: models.Model) -> models.Model:
    """Compile the model with the v2 losses and task weights."""
    model.compile(
        optimizer=optimizers.Adam(learning_rate=LEARNING_RATE),
        loss=[weighted_binary_crossentropy_no_cp, sparse_ce_localization],
        loss_weights=LOSS_WEIGHTS,
        metrics=[
            [
                metrics.BinaryAccuracy(name="accuracy"),
                metrics.Precision(name="precision"),
                metrics.Recall(name="recall"),
            ],
            [metrics.SparseCategoricalAccuracy(name="sparse_accuracy")],
        ],
    )
    return model


def unpack_predictions(predictions: Any) -> tuple[np.ndarray, np.ndarray]:
    """Return has_cp probabilities and localization distributions."""
    if isinstance(predictions, (list, tuple)):
        return predictions[0], predictions[1]
    return predictions["has_cp"], predictions["cp_dist"]


def detection_metrics(y_true: np.ndarray, probabilities: np.ndarray, threshold: float) -> dict[str, Any]:
    """Compute binary detection metrics for one decision threshold."""
    y_true = np.asarray(y_true).reshape(-1).astype(int)
    probabilities = np.asarray(probabilities).reshape(-1)
    y_pred = (probabilities >= threshold).astype(int)
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred, labels=[0, 1]).ravel()

    return {
        "threshold": float(threshold),
        "accuracy": float(accuracy_score(y_true, y_pred)),
        "precision": float(precision_score(y_true, y_pred, zero_division=0)),
        "recall": float(recall_score(y_true, y_pred, zero_division=0)),
        "f1_score": float(f1_score(y_true, y_pred, zero_division=0)),
        "false_positive_rate": float(fp / (fp + tn + 1e-8)),
        "false_negative_rate": float(fn / (fn + tp + 1e-8)),
        "jaccard_coefficient": float(tp / (tp + fp + fn + 1e-8)),
        "true_negatives": int(tn),
        "false_positives": int(fp),
        "false_negatives": int(fn),
        "true_positives": int(tp),
    }


def soft_positions(cp_dist: np.ndarray) -> np.ndarray:
    """Convert a discrete localization distribution into a soft position."""
    positions = np.arange(cp_dist.shape[1], dtype=np.float32)
    return np.sum(cp_dist * positions.reshape(1, -1), axis=1) + 1.0


def localization_metrics(
    metadata: pd.DataFrame,
    probabilities: np.ndarray,
    cp_dist: np.ndarray,
    threshold: float,
) -> dict[str, Any]:
    """Compute localization MAE/RMSE on all positive trajectories and true positives."""
    y_true_has = metadata["has_changepoint"].to_numpy(dtype=int)
    y_pred_has = (np.asarray(probabilities).reshape(-1) >= threshold).astype(int)
    pred_cp = soft_positions(cp_dist)

    mask_all = y_true_has == 1
    mask_tp = (y_true_has == 1) & (y_pred_has == 1)

    def compute(mask: np.ndarray, prefix: str) -> dict[str, Any]:
        if int(mask.sum()) == 0:
            return {f"{prefix}_n": 0, f"{prefix}_mae": np.nan, f"{prefix}_rmse": np.nan}
        true_cp = metadata.loc[mask, "cp"].to_numpy(dtype=np.float32)
        return {
            f"{prefix}_n": int(mask.sum()),
            f"{prefix}_mae": float(mean_absolute_error(true_cp, pred_cp[mask])),
            f"{prefix}_rmse": float(np.sqrt(mean_squared_error(true_cp, pred_cp[mask]))),
        }

    values: dict[str, Any] = {}
    values.update(compute(mask_all, "all_changepoint"))
    values.update(compute(mask_tp, "true_positive"))
    return values


def threshold_table(
    y_true: np.ndarray,
    probabilities: np.ndarray,
    cp_dist: np.ndarray,
    metadata: pd.DataFrame,
    thresholds: np.ndarray = THRESHOLDS,
) -> pd.DataFrame:
    """Evaluate all validation thresholds."""
    rows = []
    for threshold in thresholds:
        row = detection_metrics(y_true, probabilities, threshold)
        row.update(localization_metrics(metadata, probabilities, cp_dist, threshold))
        rows.append(row)
    return pd.DataFrame(rows)


def choose_threshold(table: pd.DataFrame) -> dict[str, Any]:
    """Select the threshold using the same rule as the v2 notebook."""
    candidates = table[(table["false_positive_rate"] <= 0.35) & (table["recall"] >= 0.65)].copy()

    if candidates.empty:
        candidates = table[(table["false_positive_rate"] <= 0.45) & (table["recall"] >= 0.60)].copy()

    if candidates.empty:
        candidates = table.copy()

    candidates = candidates.sort_values(
        ["f1_score", "false_positive_rate", "precision"],
        ascending=[False, True, False],
    )
    return candidates.iloc[0].to_dict()


def selection_score(best: dict[str, Any]) -> float:
    """Validation model-selection score copied from ConvTransformer-v2."""
    return float(
        best["all_changepoint_mae"]
        + 20.0 * (1.0 - best["f1_score"])
        + 18.0 * best["false_positive_rate"]
        + 10.0 * max(0.0, 0.70 - best["recall"])
    )


class ValidationMetricsCallback(callbacks.Callback):
    """Compute thresholded validation metrics at the end of each epoch."""

    def __init__(
        self,
        x_val: np.ndarray,
        y_has_val: np.ndarray,
        val_metadata: pd.DataFrame,
        batch_size: int = 2048,
    ):
        super().__init__()
        self.x_val = x_val
        self.y_has_val = y_has_val.reshape(-1).astype(int)
        self.val_metadata = val_metadata.reset_index(drop=True)
        self.batch_size = batch_size
        self.records: list[dict[str, Any]] = []

    def on_epoch_end(self, epoch: int, logs: dict[str, Any] | None = None) -> None:
        logs = logs or {}
        has_prob, cp_dist = unpack_predictions(self.model.predict(self.x_val, batch_size=self.batch_size, verbose=0))
        has_prob = np.asarray(has_prob).reshape(-1)
        cp_dist = np.asarray(cp_dist)

        table = threshold_table(self.y_has_val, has_prob, cp_dist, self.val_metadata, THRESHOLDS)
        best = choose_threshold(table)
        score = selection_score(best)

        record = {
            "epoch": epoch + 1,
            "val_best_threshold": float(best["threshold"]),
            "val_detection_accuracy": float(best["accuracy"]),
            "val_detection_precision": float(best["precision"]),
            "val_detection_recall": float(best["recall"]),
            "val_detection_f1": float(best["f1_score"]),
            "val_false_positive_rate": float(best["false_positive_rate"]),
            "val_false_negative_rate": float(best["false_negative_rate"]),
            "val_jaccard_coefficient": float(best["jaccard_coefficient"]),
            "val_localization_mae_all_cp": float(best["all_changepoint_mae"]),
            "val_localization_rmse_all_cp": float(best["all_changepoint_rmse"]),
            "val_localization_mae_true_positive": float(best["true_positive_mae"]),
            "val_localization_rmse_true_positive": float(best["true_positive_rmse"]),
            "val_selection_score": float(score),
        }
        self.records.append(record)
        logs.update({k: v for k, v in record.items() if k != "epoch"})

        print(
            f"\nval_threshold={record['val_best_threshold']:.2f} | "
            f"F1={record['val_detection_f1']:.4f} | "
            f"recall={record['val_detection_recall']:.4f} | "
            f"FPR={record['val_false_positive_rate']:.4f} | "
            f"RMSE_TP={record['val_localization_rmse_true_positive']:.2f}"
        )


def write_yaml_like(path: Path, config: dict[str, Any]) -> None:
    """Write a small YAML file without requiring PyYAML."""

    def scalar(value: Any) -> str:
        if isinstance(value, bool):
            return "true" if value else "false"
        if value is None:
            return "null"
        if isinstance(value, (int, float)):
            return str(value)
        return str(value)

    def write_block(lines: list[str], key: str, value: Any, indent: int = 0) -> None:
        prefix = " " * indent
        if isinstance(value, dict):
            lines.append(f"{prefix}{key}:")
            for child_key, child_value in value.items():
                write_block(lines, str(child_key), child_value, indent + 2)
        elif isinstance(value, list):
            lines.append(f"{prefix}{key}:")
            for item in value:
                if isinstance(item, dict):
                    lines.append(f"{prefix}  -")
                    for child_key, child_value in item.items():
                        write_block(lines, str(child_key), child_value, indent + 4)
                else:
                    lines.append(f"{prefix}  - {scalar(item)}")
        else:
            lines.append(f"{prefix}{key}: {scalar(value)}")

    lines: list[str] = []
    for config_key, config_value in config.items():
        write_block(lines, config_key, config_value)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(description="Train ConvTransformer-v3a L=100 and evaluate validation only.")
    parser.add_argument(
        "--data-dir",
        type=Path,
        default=PROJECT_ROOT / "data_synthetic_with_without_changepoint_dx",
        help="Directory containing train/val HDF5 files from the v2 binary dataset.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help=(
            "Directory where validation_metrics.csv and config_used.yaml will be written. "
            "By default, full runs use v3a_seed42 and reduced runs use v3a_seed42_fast."
        ),
    )
    parser.add_argument("--epochs", type=int, default=MAX_EPOCHS, help="Maximum number of epochs.")
    parser.add_argument("--batch-size", type=int, default=BATCH_SIZE, help="Training batch size.")
    parser.add_argument("--seed", type=int, default=RANDOM_SEED, help="Random seed.")
    parser.add_argument(
        "--early-stopping-patience",
        type=int,
        default=15,
        help="Early stopping patience on the validation selection score.",
    )
    parser.add_argument(
        "--reduce-lr-patience",
        type=int,
        default=6,
        help="ReduceLROnPlateau patience on the validation selection score.",
    )
    parser.add_argument(
        "--max-train-samples",
        type=int,
        default=None,
        help="Optional balanced subset size for training. Use only for fast exploratory validation.",
    )
    parser.add_argument(
        "--max-val-samples",
        type=int,
        default=None,
        help="Optional balanced subset size for validation. Use only for fast exploratory validation.",
    )
    return parser.parse_args()


def main() -> None:
    """Run the validation-only ConvTransformer-v3a experiment."""
    args = parse_args()
    set_global_seed(args.seed)

    reduced_run = args.max_train_samples is not None or args.max_val_samples is not None
    if args.output_dir is None:
        run_name = f"v3a_seed{args.seed}_fast" if reduced_run else f"v3a_seed{args.seed}"
        args.output_dir = PROJECT_ROOT / "results" / "convtransformer_v3_ablation" / run_name

    data_files = {
        "train": args.data_dir / f"train_L{LENGTH}_dim1_with_without_dx.h5",
        "val": args.data_dir / f"val_L{LENGTH}_dim1_with_without_dx.h5",
    }

    args.output_dir.mkdir(parents=True, exist_ok=True)

    config_used = {
        "experiment_name": "convtransformer_v3a_L100",
        "ablation_version": "v3a",
        "status": "validation_only_no_test_results",
        "scientific_note": (
            "ConvTransformer-v3a se evalua inicialmente en validacion con una unica semilla "
            "para comprobar si la entrada multicanal justifica continuar con las variantes v3b y v3c."
        ),
        "seed": args.seed,
        "length": LENGTH,
        "dx_length": DX_LENGTH,
        "input_shape": [DX_LENGTH, N_INPUT_CHANNELS],
        "main_task": "binary_detection_and_localization",
        "data": {
            "data_dir": str(args.data_dir),
            "train_file": str(data_files["train"]),
            "val_file": str(data_files["val"]),
            "max_train_samples": args.max_train_samples,
            "max_val_samples": args.max_val_samples,
            "reduced_run": reduced_run,
            "test_used": False,
        },
        "features": {
            "use_multichannel": True,
            "channels": CHANNEL_NAMES,
            "rolling_window": 5,
            "lag1_initial_value": 0.0,
            "uses_labels": False,
            "uses_true_changepoint": False,
            "uses_has_cp": False,
            "uses_model_identity_labels": False,
        },
        "training": {
            "batch_size": args.batch_size,
            "max_epochs": args.epochs,
            "learning_rate": LEARNING_RATE,
            "loss_weights": LOSS_WEIGHTS,
            "threshold_grid": [float(x) for x in THRESHOLDS],
            "monitor_metric": MONITOR_METRIC,
            "early_stopping_patience": args.early_stopping_patience,
            "reduce_lr_patience": args.reduce_lr_patience,
        },
        "outputs": {
            "validation_metrics": str(args.output_dir / "validation_metrics.csv"),
            "config_used": str(args.output_dir / "config_used.yaml"),
            "test_metrics": "not_created_in_phase_2a",
        },
    }
    write_yaml_like(args.output_dir / "config_used.yaml", config_used)

    print("Loading train and validation splits...")
    dx_train, y_has_train, y_cp_train, train_metadata = load_split(data_files["train"], "train")
    dx_val, y_has_val, y_cp_val, val_metadata = load_split(data_files["val"], "val")

    if args.max_train_samples is not None:
        dx_train, y_has_train, y_cp_train, train_metadata = balanced_subset(
            dx_train,
            y_has_train,
            y_cp_train,
            train_metadata,
            n_total=args.max_train_samples,
            seed=args.seed,
        )
        print(f"Using balanced training subset: {len(dx_train)} examples")

    if args.max_val_samples is not None:
        dx_val, y_has_val, y_cp_val, val_metadata = balanced_subset(
            dx_val,
            y_has_val,
            y_cp_val,
            val_metadata,
            n_total=args.max_val_samples,
            seed=args.seed + 1,
        )
        print(f"Using balanced validation subset: {len(dx_val)} examples")

    print("Building multichannel features...")
    x_train = build_multichannel_features(dx_train)
    x_val = build_multichannel_features(dx_val)

    expected_train_shape = (dx_train.shape[0], DX_LENGTH, N_INPUT_CHANNELS)
    expected_val_shape = (dx_val.shape[0], DX_LENGTH, N_INPUT_CHANNELS)
    if x_train.shape != expected_train_shape:
        raise RuntimeError(f"Unexpected train feature shape {x_train.shape}; expected {expected_train_shape}.")
    if x_val.shape != expected_val_shape:
        raise RuntimeError(f"Unexpected validation feature shape {x_val.shape}; expected {expected_val_shape}.")

    print("Train features:", x_train.shape)
    print("Validation features:", x_val.shape)

    train_ds = make_dataset(x_train, y_has_train, y_cp_train, batch_size=args.batch_size, training=True)
    val_ds = make_dataset(x_val, y_has_val, y_cp_val, batch_size=args.batch_size, training=False)

    model = build_convtransformer_v3a_model(input_shape=(DX_LENGTH, N_INPUT_CHANNELS))
    compile_model(model)
    model.summary()

    val_metrics_callback = ValidationMetricsCallback(x_val, y_has_val, val_metadata)
    training_callbacks = [
        val_metrics_callback,
        callbacks.EarlyStopping(
            monitor=MONITOR_METRIC,
            patience=args.early_stopping_patience,
            mode="min",
            restore_best_weights=True,
            verbose=1,
        ),
        callbacks.ReduceLROnPlateau(
            monitor=MONITOR_METRIC,
            factor=0.5,
            patience=args.reduce_lr_patience,
            mode="min",
            min_lr=1e-6,
            verbose=1,
        ),
    ]

    print("Starting validation-only v3a training protocol.")
    print("No test split will be loaded or evaluated by this script.")
    model.fit(
        train_ds,
        validation_data=val_ds,
        epochs=args.epochs,
        callbacks=training_callbacks,
        verbose=1,
    )

    has_prob, cp_dist = unpack_predictions(model.predict(x_val, batch_size=args.batch_size, verbose=1))
    has_prob = np.asarray(has_prob).reshape(-1)
    cp_dist = np.asarray(cp_dist)

    validation_metrics = threshold_table(y_has_val, has_prob, cp_dist, val_metadata, THRESHOLDS)
    selected = choose_threshold(validation_metrics)
    selected_threshold = float(selected["threshold"])
    validation_metrics["selected"] = validation_metrics["threshold"] == selected_threshold
    validation_metrics["selection_score"] = [
        selection_score(row.to_dict()) for _, row in validation_metrics.iterrows()
    ]
    validation_metrics["experiment_name"] = "convtransformer_v3a_L100"
    validation_metrics["seed"] = args.seed
    validation_metrics["split"] = "validation"
    validation_metrics["reduced_run"] = reduced_run
    validation_metrics["train_samples"] = len(x_train)
    validation_metrics["validation_samples"] = len(x_val)
    validation_metrics.to_csv(args.output_dir / "validation_metrics.csv", index=False)

    print("Selected validation threshold:", selected_threshold)
    print("Saved:", args.output_dir / "validation_metrics.csv")
    print("Saved:", args.output_dir / "config_used.yaml")
    print("No test metrics were created.")

    summary = {
        "selected_threshold": selected_threshold,
        "selected_validation_metrics": selected,
        "output_dir": str(args.output_dir),
    }
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
